apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certbot-edit
subjects:
- kind: ServiceAccount
  name: certbot
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io